Repository The-Bugger-Ducks/help-duck-web, pull requests merged in 2022-05, with the labels that each got.

#64 Created alert for 'forgot password' on login screen. Added the functi…
  src/pages/Login/Login.tsx
  src/pages/Ticket/TicketRegister.tsx
  src/shared/styles/pages/login/Login.css
  src/shared/styles/pages/ticket/TicketRegister.css
Labels: bug

#62 Feat/the alter user page
  src/pages/Auth/Login.tsx
  src/pages/Ticket/DetailTicket.tsx
  src/pages/User/Signup.tsx
  src/pages/User/UserEdit.tsx
  src/routes.tsx
  src/shared/components/ChoiceField.tsx
  src/shared/components/Dropdown.tsx
  src/shared/components/TextField.tsx
  src/shared/components/UserList.tsx
  src/shared/styles/components/TicketList.css
  src/shared/styles/pages/auth/Login.css
  src/shared/styles/pages/user/Signup.css
  src/shared/styles/pages/user/UserEdit.css
  src/shared/utils/endpoints.ts
  src/shared/utils/requests/User.requests.ts
Labels: enhancement

#72 add solution comment view in details ticket
  src/pages/Ticket/DetailTicket.tsx
  src/shared/components/TicketSolution.tsx
  src/shared/interfaces/solution.interface.ts
  src/shared/interfaces/ticket.interface.ts
  src/shared/styles/components/TicketSolution.css
  src/shared/styles/pages/ticket/DetailTicket.css
Labels: enhancement

#75 Feat/attach solution
  src/pages/Ticket/DetailTicket.tsx
  src/shared/components/TicketComment.tsx
  src/shared/components/TicketSolution.tsx
  src/shared/interfaces/solution.interface.ts
  src/shared/interfaces/ticket.interface.ts
  src/shared/services/Api.service.ts
  src/shared/styles/components/TicketComment.css
  src/shared/utils/endpoints.ts
  src/shared/utils/requests/Solution.requests.ts
Labels: enhancement

#76 Development
  src/pages/Ticket/DetailTicket.tsx
  src/shared/components/TicketComment.tsx
  src/shared/components/TicketSolution.tsx
  src/shared/interfaces/solution.interface.ts
  src/shared/interfaces/ticket.interface.ts
  src/shared/services/Api.service.ts
  src/shared/styles/components/TicketComment.css
  src/shared/utils/endpoints.ts
  src/shared/utils/requests/Solution.requests.ts
Labels: enhancement

#91 Feat/loading
  package.json
  src/pages/Auth/Login.tsx
  src/pages/Equipment/EquipmentRegister.tsx
  src/pages/Equipment/EquipmentUpdate.tsx
  src/pages/Homepage/Homepage.tsx
  src/pages/Ticket/DetailTicket.tsx
  src/pages/Ticket/TicketRegister.tsx
  src/pages/User/Signup.tsx
  src/pages/User/UserUpdate.tsx
  src/shared/assets/animation/settings-loading-icon.json
  src/shared/assets/animation/settings-loading.json
  src/shared/components/EquipmentList.tsx
  src/shared/components/Loading/CustomTableRow.tsx
  src/shared/components/Loading/LoadingContainer.tsx
  src/shared/components/Pagination/Pagination.tsx
  src/shared/components/TicketList.tsx
  src/shared/components/TicketTable.tsx
  src/shared/components/UserList.tsx
  src/shared/interfaces/pagable.interface.ts
  src/shared/styles/components/loading/loadingContainer.css
  src/shared/styles/components/pagination.css
  src/shared/styles/global.css
  src/shared/utils/requests/User.requests.ts
  yarn.lock
Labels: enhancement

#100 implemented increment vote solution
  src/pages/Ticket/DetailTicket.tsx
  src/shared/components/TicketSolution.tsx
  src/shared/interfaces/solution.interface.ts
  src/shared/utils/endpoints.ts
  src/shared/utils/requests/Solution.requests.ts
Labels: enhancement

#104 Feat/93 front filtragem de usuários
  src/pages/Homepage/Homepage.tsx
  src/pages/Ticket/DetailTicket.tsx
  src/shared/components/UserList.tsx
  src/shared/constants/userFilterSelect.ts
  src/shared/utils/endpoints.ts
  src/shared/utils/requests/User.requests.ts
Labels: 2
